sonar.projectKey=karimkhaled842_devsecops-poc
sonar.organization=karimkhaled842
sonar.projectName=devsecops-poc
sonar.sources=app
sonar.exclusions=app/tests/**
sonar.tests=app/tests
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3.12
sonar.sourceEncoding=UTF-8